config:
  service: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File parsers_multiline.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        multiline.parser  java,multiline-regex-test
        Mem_Buf_Limit     5MB


##    [INPUT]
##        Name     syslog
##        Parser   syslog-rfc5424
##        Listen   0.0.0.0
##        Port     5140
##        Mode     udp
  ## https://docs.fluentbit.io/manual/pipeline/filters
##  filters: |
##    [FILTER]
##        Name kubernetes
##        Match kube.*
##        Merge_Log On
##        Keep_Log Off
##        K8S-Logging.Parser On
##        K8S-Logging.Exclude On

##     [FILTER]
##        name                  multiline
##        match                 *
##        multiline.key_content log
##        multiline.parser      java, multiline-regex-test

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name        datadog
        Match       *
        apikey      [API-key]
  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/upstream-servers
  ## This configuration is deprecated, please use `extraFiles` instead.
  upstream: {}

  ## https://docs.fluentbit.io/manual/pipeline/parsers
##  customParsers: |
##    [PARSER]
##        Name docker_no_time
##        Format json
##        Time_Keep Off
##        Time_Key time
##        Time_Format %Y-%m-%dT%H:%M:%S.%L

##    [PARSER]
##         Name        syslog-rfc5424
##         Format      regex
##         Regex       ^\<(?<pri>[0-9]{1,5})\>1 (?<time>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*?)\]|-)) (?<message>.+)$
##         Time_Key    time
##         Time_Format %Y-%m-%dT%H:%M:%S.%L%z
##         Time_Keep   On
